api/urls.py
# coding: utf-8

from django.conf.urls import url, patterns, include

urlpatterns = [
    url('^task_item_detail$', 'api.views.api_task_item_detail', name='task_item_detail'),
    url('^cre_user_task$', 'api.views.api_cre_user_task_item', name='cre_user_task'),
    url('^del_user_task$', 'api.views.api_del_user_task_item', name='del_user_task'),
    url('^add_user_task_memo$', 'api.views.api_add_user_task_item_memo', name='add_user_task_memo'),
    url('^do_user_task_status$', 'api.views.api_do_user_task_item_status', name='do_user_task_status'),
]

task_skill/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^rit/', include('rit.urls', namespace='rit')),
]

tasks/urls.py
# coding: utf-8

from django.conf.urls import url, patterns
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^index$', 'tasks.views.do_login', name='login'),
    url(r'^logout$', 'tasks.views.do_logout', name='logout'),
    url(r'^top', 'tasks.views.top', name='top'),
    url(r'^post', 'tasks.views.do_post', name='post'),
]

tasks/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TaskItem(models.Model):
    """読書、勉強、執筆等
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class TaskItemDetail(models.Model):
    """易しい本、普通の本
    """
    task_item = models.ForeignKey(TaskItem)
    name = models.CharField(max_length=200)
    point = models.PositiveIntegerField()

    def __str__(self):
        return self.name


#その日に使ったポイント合計

class Player(models.Model):
    """プレイヤーの属性情報
    """
    user = models.ForeignKey(User)
    level = models.PositiveIntegerField(default=1)
    skill_point = models.PositiveIntegerField(default=100)
    exp = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username + "Lv:" + str(self.level)


class PlayerTask(models.Model):
    """プレイヤーのタスク
    """
    player = models.ForeignKey(Player)
    task_item_detail = models.ForeignKey(TaskItemDetail)
    task_ymd = models.DateField()
    memo = models.TextField(max_length=1000, blank=True)

    def __str__(self):
        return self.task_item_detail.name

tasks/forms.py
# coding: utf-8
from django import forms
from tasks.models import TaskItem, TaskItemDetail


class LoginForm(forms.Form):
    username = forms.CharField(label="ユーザー",max_length=200)
    password = forms.CharField(label="パスワード",widget=forms.PasswordInput, max_length=30)


class TaskReportForm(forms.Form):
    task_item = forms.ModelChoiceField(queryset=TaskItem.objects.all())
    task_item_detail = forms.ModelChoiceField(queryset=TaskItemDetail.objects.all())
    memo = forms.CharField(widget=forms.Textarea, required=False)


    def clean(self):
        clnd = self.cleaned_data

        #if not self.is_valid():
        #    return clnd

tasks/views.py
from django.shortcuts import (render, render_to_response,
                              get_object_or_404, Http404, redirect, urlresolvers)

from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone

from tasks.forms import LoginForm, TaskReportForm
from tasks.models import PlayerTask, Player

from tasks.functions import check_task_save, get_player_task

def top(request):
    if request.method == "GET":
        form = TaskReportForm()

        return render_to_response('tasks/top.html',
                                  dict(form=form, player_task_list=get_player_task(request, timezone.now())),
                                  RequestContext(request))

def do_post(request):
    if request.method == "POST":
        form = TaskReportForm(request.POST)
        if form.is_valid():
            task_item_detail = form.cleaned_data["task_item_detail"]
            memo = form.cleaned_data["memo"]
            ymd = timezone.now()
            player_task = PlayerTask()
            player_task.task_item_detail = task_item_detail
            player_task.memo = memo
            player_task.task_ymd = ymd
            player_task.player = Player.objects.get(user__username=request.user.username)


            if check_task_save(request, task_item_detail):
                player_task.save()

                return redirect(urlresolvers.reverse_lazy('tasks:top'))
            else:
                return render_to_response('tasks/top.html',
                                          dict(form=form, player_task_list=get_player_task(request, timezone.now()),
                                               error_message="魔力が足りません"),
                                          RequestContext(request))

        else:
            return render_to_response('tasks/top.html',
                                      dict(form=form, player_task_list=get_player_task(request, timezone.now())),
                                      RequestContext(request))




def do_logout(request):
    logout(request)
    return redirect(urlresolvers.reverse_lazy('tasks:login'))


def do_login(request):

    if request.method == "GET":
        form = LoginForm()
        return render_to_response('index.html',
                                  dict(form=form),
                                  RequestContext(request)
                                  )
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                return redirect(urlresolvers.reverse_lazy('rit:top'))
            else:
                return render_to_response('index.html',
                                          dict(form=LoginForm(initial={'username':username, 'password':password}),
                                               error_message="ログインに失敗しました。"),
                                          RequestContext(request))

templates/tasks/top.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>トップページ</title>
</head>
<body>
    <a href="{% url 'tasks:top' %}">ようこそ、タスクの世界へ</a>
    <br>
    ユーザ@{{ user }} - 魔力@{{ skill_point }} - レベル@{{ level }}

    <br>
    <form action='{% url 'tasks:post' %}' method="post">
        {{ form.task_item }} {{ form.task_item_detail }}<br>
        {{ form.memo }}
        {% csrf_token %}
        <button type="submit">登録</button>
    </form>

    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    {{ error_message }}

    <br>

    <table>
        <tr>
            <th>タスク日付</th>
            <th>タスク名</th>
            <th>ポイント</th>
            <th>メモ</th>
        </tr>
    {% for player_task in player_task_list %}
        <tr>
            <td>{{ player_task.task_ymd }}</td>
            <td>{{ player_task.task_item_detail.name }}</td>
            <td>{{ player_task.task_item_detail.point }}</td>
            <td>{{ player_task.memo }}</td>
        </tr>
    {% endfor %}
    </table>

    <a href="{% url 'tasks:logout' %}">ログアウト</a>
</body>

{% include "xhr.html" %}

<script>
    $(document).ready(function() {
        var task_item_id = "id_task_item";
        var task_item_detail_id = "id_task_item_detail";
        $("#"+task_item_id).on("change", function(){
            //$.ajax({% url 'api:task_item_detail' %},
            //)
            var task_item_value = this.value;
            if(this.value == "") return;

            $.ajax({
                type: 'POST',
                dataType: 'text',
                url: '{% url 'api:task_item_detail' %}',
                data: "key="+ task_item_value,
                success: function(data) {
                    do_callback(data);
                },
                error: function(data) {
                    console.log(data);
                }
            });

            function do_callback(data) {
                console.log(data);
                var result = JSON.parse(data);
                console.log(result);

                var task_item_detail_html = "";
                var result_length = result.length;
                for(var i = 0; i < result_length; i++) {
                    console.log(result[i].name);
                    task_item_detail_html += '<option value="'+result[i].id+'">'+ result[i].name+'('+ result[i].point +')' +'</option>';
                }
                console.log(task_item_detail_html);

                $("#"+task_item_detail_id).html(task_item_detail_html);
            }

            console.log(this.value);
        });
    });
</script>

</html>